delete dbo.ComprobantesArqueos
delete dbo.Arqueos
delete dbo.ComprobantesRemesas
delete dbo.ValoresRemesas
delete dbo.Remesas
delete dbo.Cobranzas
delete dbo.ComprobantesCambioDeCobrador
delete dbo.CambiosDeCobrador
delete dbo.DetallesComprobantes
delete dbo.Comprobantes